let myCart = []

const itemData = [
  { name: 'Penne Rigatta',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkDtIE2ZlT-XAnqWLFhhq9Zb7boPQxvHlRR_Wfv3TkjiWdxyQC',
    desc: 'Whole Wheat Penne pasta with tomatoes and basil',
    type: 'entree',
    hidden: false,
    price: '9.50',
    icon1: false,
    icon2: true,
    icon3: true,
    icon4: false,
  },
  { name: 'Truffle Pasta',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMXBDjGURLnAiYoZ99_0plsyIKIJd2YCRvPHjVlPauPytoaG5Q1Q',
    desc: 'Buttered Pasta with savory organic truffles',
    type: 'entree',
    hidden: false,
    price: '17.50',
    icon1: false,
    icon2: false,
    icon3: true,
    icon4: false,
  },
  { name: 'Steak Tips',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyupMobW6mp9DTxSxqC6QDviYUA4pWOcUb9u-m3bDpnYmDiP4D',
    desc: 'Tri-tip quality steak with a house steak sauce',
    type: 'entree',
    hidden: false,
    price: '18.00',
    icon1: true,
    icon2: false,
    icon3: false,
    icon4: true,
  },
  { name: 'Chicken and Veggies',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO2wF9wpA2hNSqTr_7OTNnVzf3wOM4tlDjaPpoAeJ9GI7LMSeucA',
    desc: 'Carved Rotisseried chicken marinated in a citrusy sauce then topped with onions, bell peppers and cilantro',
    type: 'entree',
    hidden: false,
    price:'8.50',
    icon1: false,
    icon2: false,
    icon3: false,
    icon4: true,
  },
  { name: 'Central Asian pan noodles',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5ZQ981lVKqrZTAW1R4mjXEOJ5YJ5YwIlpEPbBIYTVr1Kp3pIt1g',
    desc: 'Thick rice noodles topped with broccoli and classic mongolian spices',
    type: 'side',
    hidden: false,
    price: '7.00',
    icon1: true,
    icon2: true,
    icon3: true,
    icon4: true,
  },
  { name:'Chinese dumplings',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx9L-TJT6QHPE3JKQrxMymf52WP6lxW-EkUcWOULo1mn_L0ppCQA',
    desc:'Deliciously Doughy Dumplings stuffed with veggies and Pork',
    type: 'appetizer',
    hidden: false,
    price:'6.00',
    icon1: true,
    icon2: false,
    icon3: false,
    icon4: false,
  },
  { name:'Shrimp Bangaroos',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3w1zibq6O4vt5_B_-PEmk8KdGh_5YmGrQzXc7k5MUvkl4hRO1gA',
    desc:'Fried coconut schrimp with house cocktail sauce',
    type: 'side',
    hidden: false,
    price:'7.50',
    icon1: true,
    icon2: false,
    icon3: false,
    icon4: false,
  },
  { name:"Devil's Chocolate Cake",
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMVo-OeRcXXk-d2F7ymofbRMHBJzrXx8izKbva15aWR0l9Sf1g7A',
    desc:"With high cocoa percentage and a fruity, spicy finish, this Devil's cake will have you worshiping it in no time",
    type: 'dessert',
    hidden: false,
    price:'8.00',
    icon1:true,
    icon2:false,
    icon3:true,
    icon4:false,
  },
  { name:'Pomegranate Tofu Salad',
    img: 'https://www.halfbakedharvest.com/wp-content/uploads/2018/01/Rejuvenating-Winter-Broccoli-Salad-1-500x500.jpg',
    desc:'An excellent salad topped with market fresh blackberries and grilled tofu',
    type: 'salad',
    hidden: false,
    price:'11.00',
    icon1:false,
    icon2:true,
    icon3:true,
    icon4:true,
  },
  { name:'Seattle Style Sushi',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxUromC9Zu94XcgzZUQhGlMuScWxAVyUc3F6xgmj7O9FEgdcVjwA',
    desc:'Tuna and Arbicore wrapped with mango and avocado',
    type: 'entree',
    hidden: false,
    price:'13.00',
    icon1:false,
    icon2:false,
    icon3:false,
    icon4:true,
  },
  { name:'Shrimp and brown Rice',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC7LZkkhQJubdBgpa5-nRasf2yGVeXxRl0hqmaoYHxkhmhi5Br',
    desc:'Sauteed shrimp on a bed of brown rice with edamame and chili oil',
    type: 'appetizer',
    hidden: false,
    price:'7.50',
    icon1:true,
    icon2:false,
    icon3:false,
    icon4:true,
  },
  { name:'Pizzen',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFWX5kL5VeRcZK9XzI7Br0X-mHUDCyT0238m9tQtELIUjDr5Sj',
    desc:"Everybody's Favorite round food available with just about every topping",
    type: 'entree',
    hidden: false,
    price:'14.00',
    icon1:true,
    icon2:false,
    icon3:false,
    icon4:false,
  },
  { name:'Sushi Platter',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyWXP0l8J7d_NcfNl0TvBe3GRF3OOjYE14eyYZ-HELzRIcWgEijA',
    desc:"A 'flight' of sushi with California rolls, Philadelphia Rolls, Unagi Rolls and Seattle Style rolls",
    type: 'appetizer',
    hidden: false,
    price:'18.00',
    icon1:true,
    icon2:false,
    icon3:false,
    icon4:true,
  },
  { name:'Warm Lentil Salad with Poached Egg',
    img: 'https://static01.nyt.com/images/2017/05/09/dining/09SALADGUIDE9/09SALADGUIDE9-articleLarge.jpg',
    desc:'A Paleo diet salad with nuts, lentils and herbs topped with a poached egg',
    type: 'salad',
    hidden: false,
    price:'9.50',
    icon1: false,
    icon2: true,
    icon3: true,
    icon4: true,
  },
  { name:'House Special',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQV_lAvZJF2jXxrueZyF7ac5ENnonh_5xg59m9hJ3jZempvNQI5',
    desc:'A tower of deliciousness containing shrimp, kale, flatiron steak and a secret sauce',
    type: 'entree',
    hidden: false,
    price:'13.00',
    icon1: true,
    icon2: false,
    icon3: false,
    icon4: true,
  },
]
